name: Kernel CI
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
    - "main"

jobs:
  Package_KernelSU:
    runs-on: ubuntu-latest
    env:
      KernelSU_Dir: /home/runner/work/KernelSU
      Setup_Dir: /home/runner/work/Setup_Dir
    steps:
      - name: Download KernelSU from 'SoDebug/KernelSU'
        id: get-kernelsu
        run: |
          mkdir $KernelSU_Dir
          git clone https://github.com/SoDebug/KernelSU.git $KernelSU_Dir
          cd $KernelSU_Dir
          version=$(git rev-parse --short HEAD)
          echo "{KernelSU_id}={version}" >> "$GITHUB_OUTPUT"
          
      - name: Download Patch form 'SoDebug/KernelSU'
        id: get-patch
        run: |
          mkdir $Setup_Dir 
          git clone -b setup https://github.com/SoDebug/KernelSU.git $Setup_Dir
          cd $Setup_Dir
          version=$(git rev-parse --short HEAD)
          echo "{Patch_id}={version}" >> "$GITHUB_OUTPUT"
          
      - name: Patch Kernel
        run: |
          cp $Setup_Dir/setup.sh $KernelSU_Dir/kernel/setup.sh
          
      - name: Upload KernelSU Patch
        uses: actions/upload-artifact@v3.1.2
        with:
          name: KernelSU_${{ steps.get_kernelsu.outputs.KernelSU_id }}_patch_${{ steps.get_kernelsu.outputs.Patch_id }}
          path: ${{ env.KernelSU_Dir }}
          retention-days: 5

          
      
